### ISSUE TITLE
Failed initialization on handle 13EC180

### ISSUE THREAD

**Issue by matze19999** [crocandr/docker-onedrive#1]
If the client tries to download a specific file, I get this error after 35%:

Failed initialization on handle 13EC180

It worked for the first 5 downloaded files.

**Comment by matze19999** [comment]
Nevermind, my disk had no space left 😂

But maybe you can change the error message?

**Comment by crocandr** [comment]
Ok, no problem. Sometimes it happens :D

Sorry, Onedrive (app/package) uses this error message by default, I can't change this. :(
