### ISSUE TITLE
Docker keeps restarting after synchronizing for a while

### ISSUE THREAD

**Issue by TH-Braemer** [crocandr/docker-onedrive#3]
Hi

I don't know if you can help or perhaps tell me what's wrong.

I started the OneDrive container recently today, and in the beginning it syncs fine. But after a while, it begins to restart over and over again...

![onedrive](https://user-images.githubusercontent.com/55437145/108607323-ec93f780-73bf-11eb-89d9-127b47c360e7.png)

Hope you can help

**Comment by crocandr** [comment]
Hi,

Sorry, I can't say anything magically, but try to read the README file in the repo (https://github.com/crocandr/docker-onedrive). I hope it helps.

But in short:
- run the docker container manually (docker run -ti --rm ...) to configure the sync in first time
- stop the container (maybe with ctrl-c ) when the configuration finished and the first sync is started
- run the container with docker-compose (I recommend this method)
- enjoy

I hope it helps a little and Good Luck!

**Comment by abraunegg** [comment]
@TH-Braemer , @crocandr 
This Docker container actually implements, via [Fedora](https://koji.fedoraproject.org/koji/packageinfo?packageID=26044), the onedrive client that I [develop](https://github.com/abraunegg/onedrive). The Fedora RPM packages are old/stale when compared to the current release.

@TH-Braemer 
You are potentially better off using [this](https://hub.docker.com/r/driveone/onedrive) Docker container which is the official one for the client that I develop.

The Docker container is available for:
* CentOS 7
* Debian
* Alpine

It can also be manually built for ARM platforms.

**Comment by crocandr** [comment]
@abraunegg : Thank you.
